import { Netlist } from '../../peripherals/netlist';
import { GpioBus, PIN_OUTPUT } from '../../peripherals/gpio';
const bus = new GpioBus();
const nl = new Netlist(bus);
nl.addComponent('mcu', 'mcu', { board: 'wemos-d1-mini', pins: ['D1', 'GND', '3V3', '5V'] });
nl.addComponent('r1', 'resistor', { pins: ['p1', 'p2'], resistance: 220 });
nl.addComponent('d1', 'diode', { pins: ['a', 'k'] });
nl.addComponent('led1', 'led', { pins: ['a', 'k'], forwardV: 2 });
nl.addWire('mcu.D1', 'r1.p1');
nl.addWire('r1.p2', 'd1.a');
nl.addWire('d1.k', 'led1.a');
nl.addWire('led1.k', 'mcu.GND');
bus.setMode(5, PIN_OUTPUT);
bus.write(5, 1);
console.log('mode', nl.semiBias({ id: 'd1', type: 'diode', params: {} } as any));
const s = nl.resolve();
console.log('semis', s.semis.get('d1'), 'led', s.leds.get('led1'), 'faults', s.faults.length);
